# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Dominik Bauer - Robotics Engineer
description: >- # this means to ignore newlines until "baseurl:"
  Personal website of Dominik Bauer, Robotics Engineer.
baseurl: "/" # the subpath of the site
url: "https://dkbauer.github.io" # the base hostname & protocol for the site
og_image: /assets/img/profile-pic.jpg
google_analytics: "UA-121636368-3"

header:
  pages:
    - name: Home
      slug: /
    - name: Research
    - name: Blog

footer:
  show_powered_by: false
  contact:
    - name: Email
      value: dominikb@andrew.cmu.edu
      link: mailto:dominikb@andrew.cmu.edu
  follow:
    - name: LinkedIn
      link: http://linkedin.com/in/bauerdo
    - name: GitHub
      link: http://github.com/dkbauer
    - name: Scholar
      link: https://scholar.google.com/citations?user=VZThMh0AAAAJ&hl=en
    - name: ResearchGate
      link: https://www.researchgate.net/profile/Dominik-Bauer-8



# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
